[project]
name = "rdf-rules"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Majid alDosari", email = "majid.aldosari@pnnl.gov" }
]
requires-python = ">=3.13"
dependencies = [
    'uritools',
    'rdf-engine',
     'plum', 'beartype',
    # tables
    'pandas', 'json2rdf', 'openpyxl',
    #json 
    'json2rdf', 
    # sparql
    'pyoxigraph',
    # inference & validation
    'pytqshacl',
]
[project.optional-dependencies]
dev = [
    # testing
        'rdflib', 
        'pytest', 'pytest-regressions',
    'marimo',
    ]

[project.scripts]
rdf-rules = "rdf_rules:main"

[build-system]
requires = ["uv_build>=0.11.30,<0.12.0"]
build-backend = "uv_build"
