[project]
name = "rdf-rules"
version = "2026.10.83"
description = "Create RDF data "
readme = "README.md"
authors = [
    { name = "Majid alDosari", email = "majid.aldosari@pnnl.gov" }
]
requires-python = ">=3.13"
dependencies = [
    'uritools',
    'rdf-engine',
    'loguru',
     'plum', 'beartype',
    # tables
    'pandas', 'json2rdf', 'openpyxl', 'pyarrow',
    #json 
    'json2rdf', 
    # sparql
    'pyoxigraph',
    # inference & validation
    'pyshifty',
]
[dependency-groups]
dev = [
    'fire',
    # testing
        'rdflib', 
        'pytest', 'pytest-regressions',
    'marimo',
    ]


[build-system]
requires = ["uv_build>=0.11.30,<0.12.0"]
build-backend = "uv_build"
