[project]
name = "rdf-rules"
version = "2026.8.61"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Majid alDosari", email = "majid.aldosari@pnnl.gov" }
]
requires-python = ">=3.13"
dependencies = [
    'uritools',
    'rdf-engine',
     'plum', 'beartype',
    # tables
    'pandas', 'json2rdf', 'openpyxl',
    #json 
    'json2rdf', 
    # sparql
    'pyoxigraph',
    # inference & validation
    'pytqshacl[java]',
]
[project.optional-dependencies]
dev = [
    'fire',
    # testing
        'rdflib', 
        'pytest', 'pytest-regressions',
    'pytqshacl[cli]',
    'marimo',
    ]



[build-system]
requires = ["uv_build>=0.11.30,<0.12.0"]
build-backend = "uv_build"
